name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run documentation tests
        run: cargo test --doc
      - name: Run tests (with coverage)
        run: make test-cover
      - name: Upload tests coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
